'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const source = fs.readFileSync(path.join(__dirname, 'jsonDocumentUploader.js'), 'utf8');
assert.match(source, /async function resolveSubmissionByCode\(accessToken, submissionCode\)/);
assert.match(source, /getSubmissions\(accessToken\)/);
assert.match(source, /id: found\.id,[\s\S]*code: found\.code/);
assert.match(source, /resolveSubmissionByCode\(accessToken, submissionCode\)/);
assert.match(source, /submitDocument\(accessToken, submission\.code, payload\)/);
assert.doesNotMatch(source, /submitDocument\(accessToken,\s*(?:91|207),/);
console.log('ERGANI REST submission-code resolution contract passed');
