import { Schema as _Schema, model } from "mongoose";

    const Schema = _Schema;

    const ErgazomenoiSchema = new Schema({
        team: { type: String, trim: true },
        company_kod: { type: String, trim: true },
        kodikos: { type: String, trim: true },
        energos: { type: Boolean, default: false },
        archived: { type: Boolean, default: false },
        fylo: { type: Boolean, default: false },
        eponymo: { type: String, trim: true },
        onoma: { type: String, trim: true },
        eponymo_patera: { type: String, trim: true },
        patronymo: { type: String, trim: true },
        eponymo_mhteras: { type: String, trim: true },
        mhtronymo: { type: String, trim: true },
        afm: { type: String, trim: true, length: 9 },
        doy: { type: String, trim: true },
        typos_taytothtas: { type: String, trim: true },
        adt: { type: String, trim: true },
        hmeromhnia_ekdoshs: { type: Date },
        arxh_ekdoshs: { type: String, trim: true },
        amka: { type: String, trim: true, length: 11 },
        hmeromhnia_gennhshs: { type: Date },
        topos_gennhshs: { type: String, trim: true },
        arithmos_bibliarioy_anhlikoy: { type: String, trim: true },
        yphkoothta: { type: String, trim: true },
        odos: { type: String, trim: true },
        arithmos: { type: String, trim: true },
        tk: { type: String, trim: true },
        thlefono: { type: String, trim: true },
        perifereia: { type: String, trim: true },
        nomos: { type: String, trim: true },
        dhmos: { type: String, trim: true },
        polh: { type: String, trim: true },
        email: { type: String, trim: true },
        hmeromhnia_proslhpshs: { type: Date },
        hmeromhnia_allaghs_symbashs: { type: Date },
        hmeromhnia_allaghs_orarioy_apo: { type: Date },
        hmeromhnia_allaghs_orarioy_eos: { type: Date },
        hmeromhnia_lhxhs_symbashs: { type: Date },
        hmeromhnia_apoxorhshs: { type: Date },
        kathestos_apasxolhshs: { type: String, trim: true },
        sxesh_ergasias: { type: String, trim: true },
        apasxolhsh_gia_proth_fora: { type: Boolean, default: false },
        ora_enarxhs_proths_foras: { type: String },
        ora_apoxorhshs_proths_foras: { type: String },
        karta_ergasias: { type: Boolean, default: false },
        evelikth_proselefsh: { type: Number, default: 0 },
        syggeneia: { type: Boolean, default: false },
        syggenikh_sxesh: { type: String, trim: true },
        proyphresia_se_eth: { type: Number, default: 0 },
        proyphresia_se_mhnes: { type: Number, default: 0 },
        proyphresia_adeias_se_eth: { type: Number, default: 0 },
        synolo_proyphresias_se_eth: { type: Number, default: 0 },
        synolo_proyphresias_se_mhnes: { type: Number, default: 0 },
        misthologiko_klimakio: { type: Number, default: 0 },
        plhrhs_apasxolhsh: { type: Boolean, default: false },
        dieythethsh_xronoy_ergasias: { type: Boolean, default: false },
        hmeres_ergasias_ebdomadas: { type: Number, default: 0 },
        ores_ergasias_ebdomadas: { type: Number, default: 0 },
        dialleima_se_lepta: { type: Number, default: 0 },
        dialleima_entos_ektos_orarioy: { type: Boolean, default: false },
        symbatikes_ores_ergasias: { type: Number, default: 0 },
        typos_orarioy: { type: Boolean, default: false },
        synexes_diakekomeno: { type: Boolean, default: false },
        pshfiakh_organosh: { type: Boolean, default: false },
        apasxolhsh_basei_symbashs: { type: String, trim: true },
        asfalish_me_tekmarta: { type: Boolean, default: false },
        asfalistikh_klash: { type: String, trim: true },
        epoxikos: { type: Boolean, default: false },
        tmhma: { type: String, trim: true },
        eidikh_kathgoria_ergazomenoy: { type: String, trim: true },
        oikogeneiakh_katastash: { type: String, trim: true },
        arithmos_teknon: { type: Number, default: 0 },
        ekpaideytiko_epipedo: { type: String, trim: true },
        eidikothta: { type: String, trim: true },
        antikeimeno_ergasion: { type: String, trim: true },
        typos_ergazomenon: { type: String, trim: true },
        ypokatasthma: { type: String, trim: true },
        xarakthrismos_ergazomenon: { type: Boolean, default: false },
        eidikothta_erganh: { type: String, trim: true },
        kad_efka: { type: String, trim: true },
        eidikothta_efka: { type: String, trim: true },
        kpk_efka: { type: String, trim: true },
        kpk_efka_basei_symbashs: { type: String, trim: true },
        epa_efka: { type: String, trim: true },
        meiosh_eisforon_ergazomenon: { type: Boolean, default: false },
        epidothsh_eisforon_ergodoth: { type: Boolean, default: false },
        diathesimothta: { type: Boolean, default: false },
        enarxh_diathesimothtas: { type: Date },
        lhxh_diathesimothtas: { type: Date },
        palios_neos: { type: Boolean, default: false },
        amoibetai_me_sse: { type: Boolean, default: false },
        trapeza: { type: String, trim: true },
        iban: { type: String, trim: true },
        arithmos_deltioy_anergias: { type: String, trim: true },
        systatiko_shmeioma: { type: Boolean, default: false },
        programma_dypa: { type: String, trim: true },
        egkritikh_apofash_dypa: { type: String, trim: true },
        hmeromhnia_enarxhs_programmatos: { type: Date },
        hmeromhnia_lhxhs_programmatos: { type: Date },
        antikatastash_ergazomenoy: { type: Boolean, default: false },
        afm_antikatastath: { type: String, trim: true, length: 9 },
        amka_antikatastath: { type: String, trim: true, length: 11 },
        epidoma_anergias: { type: Boolean, default: false },
        dypa: { type: String, trim: true },
        thesh_eythynhs: { type: String, trim: true },
        eidikh_periptosh: { type: String, trim: true },
        kentro_kostoys_1: { type: String, trim: true },
        pososto_apasxolhshs_kk1: { type: Number, default: 0 },
        kentro_kostoys_2: { type: String, trim: true },
        pososto_apasxolhshs_kk2: { type: Number, default: 0 },
        kentro_kostoys_3: { type: String, trim: true },
        pososto_apasxolhshs_kk3: { type: Number, default: 0 },
        kentro_kostoys_4: { type: String, trim: true },
        pososto_apasxolhshs_kk4: { type: Number, default: 0 },
        symbash: { type: String, trim: true },
        kathgoria_symbashs: { type: String, trim: true },
        eidikothta_symbashs: { type: String, trim: true },
        stoixeio_symbashs_01: { type: String, trim: true },
        stoixeio_symbashs_02: { type: String, trim: true },
        stoixeio_symbashs_03: { type: String, trim: true },
        stoixeio_symbashs_04: { type: String, trim: true },
        stoixeio_symbashs_05: { type: String, trim: true },
        stoixeio_symbashs_06: { type: String, trim: true },
        stoixeio_symbashs_07: { type: String, trim: true },
        stoixeio_symbashs_08: { type: String, trim: true },
        stoixeio_symbashs_09: { type: String, trim: true },
        stoixeio_symbashs_10: { type: String, trim: true },
        stoixeio_symbashs_11: { type: String, trim: true },
        stoixeio_symbashs_12: { type: String, trim: true },
        stoixeio_symbashs_13: { type: String, trim: true },
        stoixeio_symbashs_14: { type: String, trim: true },
        stoixeio_symbashs_15: { type: String, trim: true },
        poso_symbashs_01: { type: Number, default: 0 },
        poso_symbashs_02: { type: Number, default: 0 },
        poso_symbashs_03: { type: Number, default: 0 },
        poso_symbashs_04: { type: Number, default: 0 },
        poso_symbashs_05: { type: Number, default: 0 },
        poso_symbashs_06: { type: Number, default: 0 },
        poso_symbashs_07: { type: Number, default: 0 },
        poso_symbashs_08: { type: Number, default: 0 },
        poso_symbashs_09: { type: Number, default: 0 },
        poso_symbashs_10: { type: Number, default: 0 },
        poso_symbashs_11: { type: Number, default: 0 },
        poso_symbashs_12: { type: Number, default: 0 },
        poso_symbashs_13: { type: Number, default: 0 },
        poso_symbashs_14: { type: Number, default: 0 },
        poso_symbashs_15: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_01: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_02: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_03: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_04: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_05: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_06: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_07: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_08: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_09: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_10: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_11: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_12: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_13: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_14: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_15: { type: Number, default: 0 },
        synolo_symbashs: { type: Number, default: 0 },
        synolo_symbashs_basei_oron_ergasias: { type: Number, default: 0 },
        nomimosMisthos: { type: Number, default: 0 },
        nomimoHmeromisthio: { type: Number, default: 0 },
        nomimoOromisthio: { type: Number, default: 0 },
        pragmatikosMisthos: { type: Number, default: 0 },
        pragmatikoHmeromisthio: { type: Number, default: 0 },
        pragmatikoOromisthio: { type: Number, default: 0 },
        krathsh_01: { type: String, trim: true },
        ama_krathshs_01: { type: String, trim: true },
        krathsh_02: { type: String, trim: true },
        ama_krathshs_02: { type: String, trim: true },
        krathsh_03: { type: String, trim: true },
        ama_krathshs_03: { type: String, trim: true },
        krathsh_04: { type: String, trim: true },
        ama_krathshs_04: { type: String, trim: true },
        krathsh_05: { type: String, trim: true },
        ama_krathshs_05: { type: String, trim: true },
        krathsh_06: { type: String, trim: true },
        ama_krathshs_06: { type: String, trim: true },
        krathsh_07: { type: String, trim: true },
        ama_krathshs_07: { type: String, trim: true },
        hmeromhnia_lhxhs_nomimopoihtikoy_eggrafoy: { type: Date },
        adeia_diamonhs_me_amesh_prosbash_gia_ergasia: { type: Boolean, default: false },
        eidos_adeias_diamonhs_me_amesh_prosbash_gia_ergasia: { type: String, trim: true },
        arithmos_adeias_diamonhs_me_amesh_prosbash_gia_ergasia: { type: String, trim: true },
        hmeromhnia_lhxhs_adeias_diamonhs_me_amesh_prosbash_gia_ergasia: { type: Date },
        adeia_diamonhs_xwris_amesh_prosbash_gia_ergasia: { type: Boolean, default: false },
        eidos_adeias_diamonhs_xwris_amesh_prosbash_gia_ergasia: { type: String, trim: true },
        arithmos_adeias_diamonhs_xwris_amesh_prosbash_gia_ergasia: { type: String, trim: true },
        hmeromhnia_lhxhs_adeias_diamonhs_xwris_amesh_prosbash_gia_ergasia: { type: Date },
        adeia_eisodoy_gia_epoxikh_apasxolhsh: { type: Boolean, default: false },
        arithmos_adeias_eisodoy_gia_epoxikh_apasxolhsh: { type: String, trim: true },
        apo_hmeromhnia_eisodoy_gia_epoxikh_apasxolhsh: { type: Date },
        eos_hmeromhnia_eisodoy_gia_epoxikh_apasxolhsh: { type: Date },
        epaggelmatikh_katartish: { type: Boolean, default: false },
        antikeimeno_katartishs: { type: String, trim: true },
        thematiko_pedio: { type: String, trim: true },
        thematikh_enothta: { type: String, trim: true },
        foreas_katartishs: { type: String, trim: true },
        katartish_apo: { type: Date },
        katartish_eos: { type: Date },
        diarkeia_se_ores: { type: Number, default: 0 },
        etos_apokthshs: { type: Number, default: 0 },
        allh_glossa_01: { type: String, trim: true },
        allh_glossa_02: { type: String, trim: true },
        allh_glossa_03: { type: String, trim: true },
        allh_glossa_04: { type: String, trim: true },
        gnosh_ypologiston: { type: Boolean, default: false },
        allo_proson: { type: String, trim: true },
        oros_sth_symbash_n_3986_2011: { type: Boolean, default: false },
        kataggelia_katopin_eggrafhs_proeidopoihshs: { type: Boolean, default: false },
        hmeromhnia_eggrafhs_proeidopoihshs: { type: Date },
        omadikh_apolysh: { type: Boolean, default: false },
        arithmos_apofashs_gia_omadikh_apolysh: { type: String, trim: true },
        hmeromhnia_apofashs_gia_omadikh_apolysh: { type: Date },
        epidosh_me_dikastiko_epimelhth: { type: Boolean, default: false },
        hmeromhnia_epidoshs: { type: Date },
        hmeromhnia_katabolhs_ths_apozhmioshs: { type: Date },
        shmeioseis_apozhmioshs: { type: String, trim: true },
        parathrhseis: { type: String, trim: true },
        symfonhtheis_misthos_genikos: { type: Number, default: 0 },
        symfonhtheis_misthos_apasxolhseis: { type: Number, default: 0 },
        paketo_apodoxon: { type: Number, default: 0 },
        mhniaia_repo: { type: Number, default: 0 },
        createdAt: { type: Date, default: Date.now() },
        updatedAt: { type: Date, default: Date.now() },
        ypologismos_foroy: { type: Boolean, default: false },
    });

    ErgazomenoiSchema.index(
        { team: 1, company_kod: 1, ypokatasthma: 1, kodikos: 1 },
        { partialFilterExpression: { archived: false, energos: true } }
      );
      
      // 2. Ανενεργοί / αρχειοθετημένοι (για ιστορικό, admin προβολή)
      ErgazomenoiSchema.index(
        { team: 1, company_kod: 1, kodikos: 1 },
        { partialFilterExpression: { archived: true } }
      );
              
    const ErgazomenoiModel = model("Ergazomenoi", ErgazomenoiSchema);

    const OrariaSchema = new Schema({
        team: { type: String, trim: true },
        company_kod: { type: String, trim: true },
        kodikos: { type: String, trim: true },
        hmeromhnia: { type: Date },
        kathgoria_ergasias: { type: String, trim: true },
        apo_ora_01: { type: String },
        eos_ora_01: { type: String },
        apo_ora_02: { type: String },
        eos_ora_02: { type: String },
        apo_ora_03: { type: String },
        eos_ora_03: { type: String },
        dialleima_apo_ora_01: { type: String },
        dialleima_eos_ora_01: { type: String },
        dialleima_apo_ora_02: { type: String },
        dialleima_eos_ora_02: { type: String },
        dialleima_apo_ora_03: { type: String },
        dialleima_eos_ora_03: { type: String },
        repo: { type: Boolean, default: false },
        adeia: { type: Boolean, default: false },
        astheneia: { type: Boolean, default: false },
        argia: { type: Boolean, default: false },
        perigrafh_argias: { type: String, trim: true },
        kathgoria_adeias: { type: String, trim: true },
        ores_ergasias: { type: Number, default: 0 },
        ores_nyxtas: { type: Number, default: 0 },
        ores_argion: { type: Number, default: 0 },
        ores_yperergasias: { type: Number, default: 0 },
        ores_yperergasias_nyxtas: { type: Number, default: 0 },
        ores_yperergasias_argion: { type: Number, default: 0 },
        ores_yperergasias_argion_nyxtas: { type: Number, default: 0 },
        ores_nominhs_yperorias: { type: Number, default: 0 },
        ores_nominhs_yperorias_nyxtas: { type: Number, default: 0 },
        ores_nominhs_yperorias_argion: { type: Number, default: 0 },
        ores_nominhs_yperorias_argion_nyxtas: { type: Number, default: 0 },
        ores_paranomhs_yperorias: { type: Number, default: 0 },
        ores_paranomhs_yperorias_nyxtas: { type: Number, default: 0 },
        ores_paranomhs_yperorias_argion: { type: Number, default: 0 },
        ores_paranomhs_yperorias_argion_nyxtas: { type: Number, default: 0 },
    });

        OrariaSchema.index({
        team: 1,
        company_kod: 1,
        kodikos: 1,
        hmeromhnia: 1
      }, { unique: false }); 
      
    const OrariaModel = model("Oraria", OrariaSchema);

    const OrariaFromCardsSchema = new Schema({
        team: { type: String, trim: true },
        company_kod: { type: String, trim: true },
        kodikos: { type: String, trim: true },
        hmeromhnia: { type: Date },
        kathgoria_ergasias: { type: String, trim: true },
        apo_ora_01: { type: String },
        eos_ora_01: { type: String },
        apo_ora_02: { type: String },
        eos_ora_02: { type: String },
        apo_ora_03: { type: String },
        eos_ora_03: { type: String },
        dialleima_apo_ora_01: { type: String },
        dialleima_eos_ora_01: { type: String },
        dialleima_apo_ora_02: { type: String },
        dialleima_eos_ora_02: { type: String },
        dialleima_apo_ora_03: { type: String },
        dialleima_eos_ora_03: { type: String },
        repo: { type: Boolean, default: false },
        adeia: { type: Boolean, default: false },
        astheneia: { type: Boolean, default: false },
        argia: { type: Boolean, default: false },
        perigrafh_argias: { type: String, trim: true },
        kathgoria_adeias: { type: String, trim: true },
        ores_ergasias: { type: Number, default: 0 },
        ores_nyxtas: { type: Number, default: 0 },
        ores_argion: { type: Number, default: 0 },
        ores_yperergasias: { type: Number, default: 0 },
        ores_yperergasias_nyxtas: { type: Number, default: 0 },
        ores_yperergasias_argion: { type: Number, default: 0 },
        ores_yperergasias_argion_nyxtas: { type: Number, default: 0 },
        ores_nominhs_yperorias: { type: Number, default: 0 },
        ores_nominhs_yperorias_nyxtas: { type: Number, default: 0 },
        ores_nominhs_yperorias_argion: { type: Number, default: 0 },
        ores_nominhs_yperorias_argion_nyxtas: { type: Number, default: 0 },
        ores_paranomhs_yperorias: { type: Number, default: 0 },
        ores_paranomhs_yperorias_nyxtas: { type: Number, default: 0 },
        ores_paranomhs_yperorias_argion: { type: Number, default: 0 },
        ores_paranomhs_yperorias_argion_nyxtas: { type: Number, default: 0 },
    });
    const OrariaFromCardsModel = model("OrariaFromCards", OrariaFromCardsSchema);

    const OrariaApologistikaSchema = new Schema({
        team: { type: String, trim: true },
        company_kod: { type: String, trim: true },
        kodikos: { type: String, trim: true },
        hmeromhnia: { type: Date },
        kathgoria_ergasias: { type: String, trim: true },
        apo_ora_01_oraria: { type: String },
        eos_ora_01_oraria: { type: String },
        apo_ora_02_oraria: { type: String },
        eos_ora_02_oraria: { type: String },
        apo_ora_03_oraria: { type: String },
        eos_ora_03_oraria: { type: String },
        dialleima_apo_ora_01_oraria: { type: String },
        dialleima_eos_ora_01_oraria: { type: String },
        dialleima_apo_ora_02_oraria: { type: String },
        dialleima_eos_ora_02_oraria: { type: String },
        dialleima_apo_ora_03_oraria: { type: String },
        dialleima_eos_ora_03_oraria: { type: String },
        repo_oraria: { type: Boolean, default: false },
        adeia_oraria: { type: Boolean, default: false },
        astheneia_oraria: { type: Boolean, default: false },
        argia_oraria: { type: Boolean, default: false },
        perigrafh_argias_oraria: { type: String, trim: true },
        kathgoria_adeias_oraria: { type: String, trim: true },
        ores_ergasias_oraria: { type: Number, default: 0 },
        ores_nyxtas_oraria: { type: Number, default: 0 },
        ores_argion_oraria: { type: Number, default: 0 },
        ores_yperergasias_oraria: { type: Number, default: 0 },
        ores_yperergasias_nyxtas_oraria: { type: Number, default: 0 },
        ores_yperergasias_argion_oraria: { type: Number, default: 0 },
        ores_yperergasias_argion_nyxtas_oraria: { type: Number, default: 0 },
        ores_nominhs_yperorias_oraria: { type: Number, default: 0 },
        ores_nominhs_yperorias_nyxtas_oraria: { type: Number, default: 0 },
        ores_nominhs_yperorias_argion_oraria: { type: Number, default: 0 },
        ores_nominhs_yperorias_argion_nyxtas_oraria: { type: Number, default: 0 },
        ores_paranomhs_yperorias_oraria: { type: Number, default: 0 },
        ores_paranomhs_yperorias_nyxtas_oraria: { type: Number, default: 0 },
        ores_paranomhs_yperorias_argion_oraria: { type: Number, default: 0 },
        ores_paranomhs_yperorias_argion_nyxtas_oraria: { type: Number, default: 0 },
        apo_ora_01_cards: { type: String },
        eos_ora_01_cards: { type: String },
        apo_ora_02_cards: { type: String },
        eos_ora_02_cards: { type: String },
        apo_ora_03_cards: { type: String },
        eos_ora_03_cards: { type: String },
        dialleima_apo_ora_01_cards: { type: String },
        dialleima_eos_ora_01_cards: { type: String },
        dialleima_apo_ora_02_cards: { type: String },
        dialleima_eos_ora_02_cards: { type: String },
        dialleima_apo_ora_03_cards: { type: String },
        dialleima_eos_ora_03_cards: { type: String },
        repo_cards: { type: Boolean, default: false },
        adeia_cards: { type: Boolean, default: false },
        astheneia_cards: { type: Boolean, default: false },
        argia_cards: { type: Boolean, default: false },
        perigrafh_argias_cards: { type: String, trim: true },
        kathgoria_adeias_cards: { type: String, trim: true },
        ores_ergasias_cards: { type: Number, default: 0 },
        ores_nyxtas_cards: { type: Number, default: 0 },
        ores_argion_cards: { type: Number, default: 0 },
        ores_yperergasias_cards: { type: Number, default: 0 },
        ores_yperergasias_nyxtas_cards: { type: Number, default: 0 },
        ores_yperergasias_argion_cards: { type: Number, default: 0 },
        ores_yperergasias_argion_nyxtas_cards: { type: Number, default: 0 },
        ores_nominhs_yperorias_cards: { type: Number, default: 0 },
        ores_nominhs_yperorias_nyxtas_cards: { type: Number, default: 0 },
        ores_nominhs_yperorias_argion_cards: { type: Number, default: 0 },
        ores_nominhs_yperorias_argion_nyxtas_cards: { type: Number, default: 0 },
        ores_paranomhs_yperorias_cards: { type: Number, default: 0 },
        ores_paranomhs_yperorias_nyxtas_cards: { type: Number, default: 0 },
        ores_paranomhs_yperorias_argion_cards: { type: Number, default: 0 },
        ores_paranomhs_yperorias_argion_nyxtas_cards: { type: Number, default: 0 },
        apo_ora_01_apologistika: { type: String },
        eos_ora_01_apologistika: { type: String },
        apo_ora_02_apologistika: { type: String },
        eos_ora_02_apologistika: { type: String },
        apo_ora_03_apologistika: { type: String },
        eos_ora_03_apologistika: { type: String },
        dialleima_apo_ora_01_apologistika: { type: String },
        dialleima_eos_ora_01_apologistika: { type: String },
        dialleima_apo_ora_02_apologistika: { type: String },
        dialleima_eos_ora_02_apologistika: { type: String },
        dialleima_apo_ora_03_apologistika: { type: String },
        dialleima_eos_ora_03_apologistika: { type: String },
        repo_apologistika: { type: Boolean, default: false },
        adeia_apologistika: { type: Boolean, default: false },
        astheneia_apologistika: { type: Boolean, default: false },
        argia_apologistika: { type: Boolean, default: false },
        perigrafh_argias_apologistika: { type: String, trim: true },
        kathgoria_adeias_apologistika: { type: String, trim: true },
        ores_ergasias_apologistika: { type: Number, default: 0 },
        ores_nyxtas_apologistika: { type: Number, default: 0 },
        ores_argion_apologistika: { type: Number, default: 0 },
        ores_yperergasias_apologistika: { type: Number, default: 0 },
        ores_yperergasias_nyxtas_apologistika: { type: Number, default: 0 },
        ores_yperergasias_argion_apologistika: { type: Number, default: 0 },
        ores_yperergasias_argion_nyxtas_apologistika: { type: Number, default: 0 },
        ores_nominhs_yperorias_apologistika: { type: Number, default: 0 },
        ores_nominhs_yperorias_nyxtas_apologistika: { type: Number, default: 0 },
        ores_nominhs_yperorias_argion_apologistika: { type: Number, default: 0 },
        ores_nominhs_yperorias_argion_nyxtas_apologistika: { type: Number, default: 0 },
        ores_paranomhs_yperorias_apologistika: { type: Number, default: 0 },
        ores_paranomhs_yperorias_nyxtas_apologistika: { type: Number, default: 0 },
        ores_paranomhs_yperorias_argion_apologistika: { type: Number, default: 0 },
        ores_paranomhs_yperorias_argion_nyxtas_apologistika: { type: Number, default: 0 },
        apologitiko_biblio: { type: Boolean, default: false },
    });

    OrariaApologistikaSchema.index({
        team: 1,
        company_kod: 1,
        kodikos: 1,
        hmeromhnia: 1
      }, { unique: false }); 
      
    const OrariaApologistikaModel = model("OrariaApologistika", OrariaApologistikaSchema);

    const IstorikoProslhpseonAllagonSchema = new Schema({
        team: { type: String, trim: true },
        company_kod: { type: String, trim: true },
        kodikos: { type: String, trim: true },
        aa_eggrafhs: { type: String, trim: true },
        hmeromhnia_proslhpshs: { type: Date },
        hmeromhnia_allaghs_symbashs: { type: Date },
        hmeromhnia_allaghs_orarioy_apo: { type: Date },
        hmeromhnia_allaghs_orarioy_eos: { type: Date },
        hmeromhnia_lhxhs_symbashs: { type: Date },
        hmeromhnia_apoxorhshs: { type: Date },
        afora_proslhpsh: { type: Boolean, default: false },
        kathestos_apasxolhshs: { type: String, trim: true },
        misthologiko_klimakio: { type: Number, default: 0 },
        symbash: { type: String, trim: true },
        kathgoria_symbashs: { type: String, trim: true },
        eidikothta_symbashs: { type: String, trim: true },
        stoixeio_symbashs_01: { type: String, trim: true },
        stoixeio_symbashs_02: { type: String, trim: true },
        stoixeio_symbashs_03: { type: String, trim: true },
        stoixeio_symbashs_04: { type: String, trim: true },
        stoixeio_symbashs_05: { type: String, trim: true },
        stoixeio_symbashs_06: { type: String, trim: true },
        stoixeio_symbashs_07: { type: String, trim: true },
        stoixeio_symbashs_08: { type: String, trim: true },
        stoixeio_symbashs_09: { type: String, trim: true },
        stoixeio_symbashs_10: { type: String, trim: true },
        stoixeio_symbashs_11: { type: String, trim: true },
        stoixeio_symbashs_12: { type: String, trim: true },
        stoixeio_symbashs_13: { type: String, trim: true },
        stoixeio_symbashs_14: { type: String, trim: true },
        stoixeio_symbashs_15: { type: String, trim: true },
        poso_symbashs_01: { type: Number, default: 0 },
        poso_symbashs_02: { type: Number, default: 0 },
        poso_symbashs_03: { type: Number, default: 0 },
        poso_symbashs_04: { type: Number, default: 0 },
        poso_symbashs_05: { type: Number, default: 0 },
        poso_symbashs_06: { type: Number, default: 0 },
        poso_symbashs_07: { type: Number, default: 0 },
        poso_symbashs_08: { type: Number, default: 0 },
        poso_symbashs_09: { type: Number, default: 0 },
        poso_symbashs_10: { type: Number, default: 0 },
        poso_symbashs_11: { type: Number, default: 0 },
        poso_symbashs_12: { type: Number, default: 0 },
        poso_symbashs_13: { type: Number, default: 0 },
        poso_symbashs_14: { type: Number, default: 0 },
        poso_symbashs_15: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_01: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_02: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_03: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_04: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_05: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_06: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_07: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_08: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_09: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_10: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_11: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_12: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_13: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_14: { type: Number, default: 0 },
        poso_symbashs_basei_oron_ergasias_15: { type: Number, default: 0 },
        synolo_symbashs: { type: Number, default: 0 },
        synolo_symbashs_basei_oron_ergasias: { type: Number, default: 0 },
        nomimosMisthos: { type: Number, default: 0 },
        nomimoHmeromisthio: { type: Number, default: 0 },
        nomimoOromisthio: { type: Number, default: 0 },
        pragmatikosMisthos: { type: Number, default: 0 },
        pragmatikoHmeromisthio: { type: Number, default: 0 },
        pragmatikoOromisthio: { type: Number, default: 0 },
        krathsh_01: { type: String, trim: true },
        krathsh_02: { type: String, trim: true },
        krathsh_03: { type: String, trim: true },
        krathsh_04: { type: String, trim: true },
        krathsh_05: { type: String, trim: true },
        krathsh_06: { type: String, trim: true },
        krathsh_07: { type: String, trim: true },
        createdAt: { type: Date, default: Date.now() },
        updatedAt: { type: Date, default: Date.now() },
    });
    const IstorikoProslhpseonAllagonModel = model("IstorikoProslhpseonAllagon", IstorikoProslhpseonAllagonSchema);


export default { ErgazomenoiModel,
                 OrariaModel,
                 OrariaFromCardsModel,
                 OrariaApologistikaModel,
                 IstorikoProslhpseonAllagonModel,
               };