const assert = require('assert');
const { APPLY_FIELDS } = require('./apasxoliseisWeeklyRepoTransferApplyPreflightService');
const { writeWeeklyRepoTransferAtomically, auditRecord, executionRecord, rowFilter, updateDocument } = require('./apasxoliseisWeeklyRepoTransferAtomicWriterService');
const values = (repo = false) => Object.fromEntries(APPLY_FIELDS.map((field) => [field, field === 'repo_apologistika' ? repo : field === 'adeia_apologistika' ? false : field.includes('ores_') ? 0 : '']));
function plan() { return { decision: { _id: '507f1f77bcf86cd799439011', snapshot_fingerprint: 'f'.repeat(64), proposal_id: 'proposal', ypokatasthma: 'branch', employee_id: '507f191e810c19729de860eb', employee_kodikos: '001', week_start: new Date('2026-07-12'), week_end: new Date('2026-07-18') }, scope: { team: 'team', company_kod: 'company' }, source: { id: '507f1f77bcf86cd799439012', date: '2026-07-13', before: values(true), after: { ...values(false), kathgoria_ergasias_apologistika: 'ΕΡΓ' } }, target: { id: '507f1f77bcf86cd799439013', date: '2026-07-14', before: values(false), after: { ...values(true), kathgoria_ergasias_apologistika: 'ΑΝ' } }, actor: { id: '507f191e810c19729de860ea', name: 'Actor', role: 'A' }, request_id: 'request-0001', command_identity: 'c'.repeat(64) }; }
function harness(options = {}) {
    const p = plan(); const committed = { rows: { [p.source.id]: { _id: p.source.id, ...p.source.before, __v: 2, is_locked: false }, [p.target.id]: { _id: p.target.id, ...p.target.before, __v: 4, is_locked: false } }, audits: [], executions: [] }; let staged; const sessions = []; let ended = false; let updateCalls = 0;
    const session = { async withTransaction(callback) { staged = structuredClone(committed); if (options.withTransactionFailure) throw new Error('transaction'); await callback(); if (options.commitFailure) throw new Error('commit'); Object.assign(committed, staged); }, async endSession() { ended = true; } };
    const connection = { async startSession() { return session; } };
    const prodhlomenaModel = { findOne(filter) { sessions.push(['read', session]); const id = String(filter._id); const row = options[`${id === p.source.id ? 'source' : 'target'}Missing`] ? null : staged.rows[id]; return { session(received) { assert.strictEqual(received, session); return this; }, async lean() { if (!row) return null; const copy = structuredClone(row); if (options[`${id === p.source.id ? 'source' : 'target'}Locked`]) copy.is_locked = true; if (options[`${id === p.source.id ? 'source' : 'target'}Stale`]) copy.repo_apologistika = !copy.repo_apologistika; return copy; } }; }, async updateOne(filter, update, meta) { sessions.push(['update', meta.session]); updateCalls++; const source = String(filter._id) === p.source.id; if (options[`${source ? 'source' : 'target'}MatchedZero`]) return { matchedCount: 0 }; Object.assign(staged.rows[String(filter._id)], update.$set); return { matchedCount: 1 }; } };
    let auditCalls = 0; const auditModel = { async create(records, meta) { sessions.push(['audit', meta.session]); auditCalls++; if (options[`${auditCalls === 1 ? 'source' : 'target'}AuditFailure`]) throw new Error('audit'); staged.audits.push(...records); return records; } };
    const executionModel = { async create(records, meta) { sessions.push(['execution', meta.session]); if (options.executionFailure) throw new Error('execution'); staged.executions.push(...records); return records.map((record) => ({ _id: 'execution', ...record })); } };
    return { p, committed, sessions, get ended() { return ended; }, get updateCalls() { return updateCalls; }, args: { plan: p, connection, prodhlomenaModel, auditModel, executionModel, capabilityProbe: async () => options.capability !== false, now: () => new Date('2026-07-14T10:00:00Z') } };
}
async function failure(options, code) { const h = harness(options); await assert.rejects(() => writeWeeklyRepoTransferAtomically(h.args), (error) => code ? error.code === code : true); assert.strictEqual(h.committed.audits.length, 0); assert.strictEqual(h.committed.executions.length, 0); assert.strictEqual(h.committed.rows[h.p.source.id].repo_apologistika, true); assert.strictEqual(h.committed.rows[h.p.target.id].repo_apologistika, false); if (options.capability !== false) assert.strictEqual(h.ended, true); }
(async () => {
    const h = harness(); const result = await writeWeeklyRepoTransferAtomically(h.args); assert.strictEqual(result.execution_status, 'APPLIED'); assert.strictEqual(h.committed.audits.length, 2); assert.strictEqual(h.committed.executions.length, 1); assert.strictEqual(h.updateCalls, 2); assert.ok(h.sessions.every(([, session]) => session === h.sessions[0][1])); assert.strictEqual(h.ended, true);
    const timestamp = new Date('2026-07-14T10:00:00Z'); assert.deepStrictEqual(h.committed.audits[0], auditRecord(h.p, h.p.source, timestamp)); assert.deepStrictEqual(h.committed.executions[0], executionRecord(h.p, timestamp));
    assert.deepStrictEqual(Object.keys(updateDocument(h.p.source).$set), APPLY_FIELDS); assert.ok(APPLY_FIELDS.every((field) => Object.hasOwn(rowFilter(h.p, { ...h.p.source, version: 2 }), field)));
    for (const [options, code] of [[{ sourceMissing: true },'SOURCE_STALE'],[{ targetMissing: true },'TARGET_STALE'],[{ sourceStale: true },'SOURCE_STALE'],[{ targetStale: true },'TARGET_STALE'],[{ sourceLocked: true },'SOURCE_LOCKED'],[{ targetLocked: true },'TARGET_LOCKED'],[{ sourceMatchedZero: true },'SOURCE_STALE'],[{ targetMatchedZero: true },'TARGET_STALE'],[{ sourceAuditFailure: true }], [{ targetAuditFailure: true }], [{ executionFailure: true }], [{ withTransactionFailure: true }], [{ commitFailure: true }]]) await failure(options, code);
    await failure({ capability: false }, 'TRANSACTIONS_UNAVAILABLE');
    console.log('weekly repo-transfer atomic writer tests passed');
})().catch((error) => { console.error(error); process.exit(1); });
