const assert = require('assert');
const { APPLY_FIELDS, CURRENT_GUARD_FIELDS } = require('./apasxoliseisWeeklyRepoTransferApplyPreflightService');
const { writeWeeklyRepoTransferAtomically, auditRecord, executionRecord, rowFilter, updateDocument } = require('./apasxoliseisWeeklyRepoTransferAtomicWriterService');
const values = (repo = false) => Object.fromEntries(APPLY_FIELDS.map((field) => [field, field === 'repo_apologistika' ? repo : field === 'adeia_apologistika' ? false : field.includes('ores_') ? 0 : '']));
const guardValues = (repo) => ({ ...Object.fromEntries(CURRENT_GUARD_FIELDS.map((field) => [field, null])), ...values(repo), cards_ores_ergasias: 8, cards_apo_ora_01: '08:00', kathgoria_ergasias: 'ΕΡΓ', ores_nyxtas_apologistika: 1, ores_nominhs_yperorias_nyxtas_apologistika: 0 });
function plan() { return { decision: { _id: '507f1f77bcf86cd799439011', snapshot_fingerprint: 'f'.repeat(64), proposal_id: 'proposal', ypokatasthma: 'branch', employee_id: '507f191e810c19729de860eb', employee_kodikos: '001', week_start: new Date('2026-07-12'), week_end: new Date('2026-07-18') }, scope: { team: 'team', company_kod: 'company' }, source: { id: '507f1f77bcf86cd799439012', date: '2026-07-13', before: values(true), after: { ...values(false), kathgoria_ergasias_apologistika: 'ΕΡΓ' }, expected_current: guardValues(true) }, target: { id: '507f1f77bcf86cd799439013', date: '2026-07-14', before: values(false), after: { ...values(true), kathgoria_ergasias_apologistika: 'ΑΝ' }, expected_current: guardValues(false) }, actor: { id: '507f191e810c19729de860ea', name: 'Actor', role: 'A' }, request_id: 'request-0001', command_identity: 'c'.repeat(64) }; }
function comparable(left, right) { if (left instanceof Date || right instanceof Date) return new Date(left).toISOString() === new Date(right).toISOString(); if (left === null || right === null || ['string','number','boolean','undefined'].includes(typeof left) && ['string','number','boolean','undefined'].includes(typeof right)) return Object.is(left, right); return String(left) === String(right); }
function harness(options = {}) {
    const p = plan(); const row = (item, version) => ({ _id: item.id, team: p.scope.team, company_kod: p.scope.company_kod, ypokatasthma: p.decision.ypokatasthma, kodikos: p.decision.employee_kodikos, hmeromhnia: new Date(`${item.date}T00:00:00.000Z`), ...item.expected_current, __v: version, is_locked: false }); const committed = { rows: { [p.source.id]: row(p.source, 2), [p.target.id]: row(p.target, 4) }, audits: [], executions: [] }; let staged; const sessions = []; let ended = false; let startSessionCalls = 0; const writesById = { [p.source.id]: 0, [p.target.id]: 0 };
    const session = { async withTransaction(callback) { staged = structuredClone(committed); if (options.withTransactionFailure) throw new Error('transaction'); await callback(); if (options.commitFailure) throw new Error('commit'); Object.assign(committed, staged); }, async endSession() { ended = true; } };
    const connection = { async startSession() { startSessionCalls++; return session; } };
    const prodhlomenaModel = { findOne(filter) { sessions.push(['read', session]); const id = String(filter._id); const role = id === p.source.id ? 'source' : 'target'; const currentRow = options[`${role}Missing`] ? null : staged.rows[id]; return { session(received) { assert.strictEqual(received, session); return this; }, async lean() { if (!currentRow) return null; const copy = structuredClone(currentRow); if (options[`${role}Locked`]) copy.is_locked = true; if (options[`${role}Stale`]) copy.repo_apologistika = !copy.repo_apologistika; if (options[`${role}GuardField`]) copy[options[`${role}GuardField`]] = options[`${role}GuardValue`]; return copy; } }; }, async updateOne(filter, update, meta) { sessions.push(['update', meta.session]); const id = String(filter._id); const role = id === p.source.id ? 'source' : 'target'; writesById[id]++; if (options[`${role}MatchedZero`]) return { matchedCount: 0 }; const matches = Object.entries(filter).every(([field, expected]) => comparable(staged.rows[id]?.[field], expected)); if (!matches) return { matchedCount: 0 }; Object.assign(staged.rows[id], update.$set); if (update.$inc?.__v) staged.rows[id].__v += update.$inc.__v; return { matchedCount: 1 }; } };
    let auditCalls = 0; const auditModel = { async create(records, meta) { sessions.push(['audit', meta.session]); auditCalls++; if (options[`${auditCalls === 1 ? 'source' : 'target'}AuditFailure`]) throw new Error('audit'); staged.audits.push(...records); return records; } };
    const executionModel = { async create(records, meta) { sessions.push(['execution', meta.session]); if (options.executionFailure) throw new Error('execution'); staged.executions.push(...records); return records.map((record) => ({ _id: 'execution', ...record })); } };
    return { p, committed, sessions, writesById, get ended() { return ended; }, get startSessionCalls() { return startSessionCalls; }, get updateCalls() { return Object.values(writesById).reduce((sum, count) => sum + count, 0); }, args: { plan: p, connection, prodhlomenaModel, auditModel, executionModel, capabilityProbe: async () => { if (options.capabilityThrow) throw new Error('hello denied'); return options.capability !== false; }, now: () => new Date('2026-07-14T10:00:00Z') } };
}
async function failure(options, code) { const h = harness(options); await assert.rejects(() => writeWeeklyRepoTransferAtomically(h.args), (error) => code ? error.code === code : true); assert.strictEqual(h.committed.audits.length, 0); assert.strictEqual(h.committed.executions.length, 0); assert.strictEqual(h.committed.rows[h.p.source.id].repo_apologistika, true); assert.strictEqual(h.committed.rows[h.p.target.id].repo_apologistika, false); if (options.capability !== false && !options.capabilityThrow) assert.strictEqual(h.ended, true); return h; }
(async () => {
    const h = harness(); const result = await writeWeeklyRepoTransferAtomically(h.args); assert.strictEqual(result.execution_status, 'APPLIED'); assert.strictEqual(h.committed.audits.length, 2); assert.strictEqual(h.committed.executions.length, 1); assert.strictEqual(h.updateCalls, 2); assert.ok(h.sessions.every(([, session]) => session === h.sessions[0][1])); assert.strictEqual(h.ended, true);
    const timestamp = new Date('2026-07-14T10:00:00Z'); assert.deepStrictEqual(h.committed.audits[0], auditRecord(h.p, h.p.source, timestamp)); assert.deepStrictEqual(h.committed.executions[0], executionRecord(h.p, timestamp)); assert.deepStrictEqual(Object.keys(h.committed.audits[0].oldValues), APPLY_FIELDS); assert.deepStrictEqual(Object.keys(h.committed.executions[0].before_snapshot.source), APPLY_FIELDS); assert.ok(!JSON.stringify(h.committed.audits).includes('cards_ores_ergasias')); assert.ok(!JSON.stringify(h.committed.executions).includes('cards_ores_ergasias'));
    const filter = rowFilter(h.p, { ...h.p.source, version: 2 }); const update = updateDocument({ ...h.p.source, version: 2 }); assert.deepStrictEqual(Object.keys(update.$set), APPLY_FIELDS); assert.ok(CURRENT_GUARD_FIELDS.every((field) => Object.hasOwn(filter, field))); for (const field of ['cards_ores_ergasias','cards_apo_ora_01','kathgoria_ergasias','ores_nyxtas_apologistika']) assert.strictEqual(filter[field], h.p.source.expected_current[field]); assert.strictEqual(filter.__v, 2); assert.deepStrictEqual(update.$inc, { __v: 1 }); assert.ok(!Object.hasOwn(update.$set, 'cards_ores_ergasias'));
    for (const [options, code] of [[{ sourceMissing: true },'SOURCE_STALE'],[{ targetMissing: true },'TARGET_STALE'],[{ sourceStale: true },'SOURCE_STALE'],[{ targetStale: true },'TARGET_STALE'],[{ sourceLocked: true },'SOURCE_LOCKED'],[{ targetLocked: true },'TARGET_LOCKED'],[{ sourceMatchedZero: true },'SOURCE_STALE'],[{ targetMatchedZero: true },'TARGET_STALE'],[{ sourceAuditFailure: true }], [{ targetAuditFailure: true }], [{ executionFailure: true }], [{ withTransactionFailure: true }], [{ commitFailure: true }]]) await failure(options, code);
    await failure({ capability: false }, 'TRANSACTIONS_UNAVAILABLE');
    const sourceCards = await failure({ sourceGuardField: 'cards_ores_ergasias', sourceGuardValue: 7 }, 'SOURCE_STALE'); assert.strictEqual(sourceCards.writesById[sourceCards.p.target.id], 0);
    const targetCards = await failure({ targetGuardField: 'cards_apo_ora_01', targetGuardValue: '09:00' }, 'TARGET_STALE'); assert.strictEqual(targetCards.committed.rows[targetCards.p.source.id].repo_apologistika, true);
    await failure({ sourceGuardField: 'kathgoria_ergasias', sourceGuardValue: 'ΑΝ' }, 'SOURCE_STALE');
    await failure({ targetGuardField: 'ores_nominhs_yperorias_nyxtas_apologistika', targetGuardValue: 1 }, 'TARGET_STALE');
    const capabilityThrow = await failure({ capabilityThrow: true }, 'TRANSACTIONS_UNAVAILABLE'); assert.strictEqual(capabilityThrow.startSessionCalls, 0);
    console.log('weekly repo-transfer atomic writer tests passed');
})().catch((error) => { console.error(error); process.exit(1); });
